apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-project.fullname" . }}
  labels:
    {{- include "k8s-project.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-project.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-project.fullname" . }}
  apiGroup: rbac.authorization.k8s.io